apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels: 
   my: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs: 
   server: 52.36.42.135 
   path: /nfs 
