apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd
  name: httpd
spec:
  nodeName: node1
  volumes: 
  - name: mayank
    persistentVolumeClaim: 
     claimName: myclaim
  containers:
  - image: httpd
    name: httpd
    volumeMounts: 
    - name: mayank 
      mountPath: /usr/local/apache2/htdocs/
