apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels: 
   my: pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
   path: /code
   type: DirectoryOrCreate
