apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchExpressions:
    - { key: app, operator: In, values: [nginx, frontend] }
    - { key: environment, operator: NotIn, values:  [production] }
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
