apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: cassandra
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress: 
  - to:
    ports: 
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP

