apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-ns
  namespace: test
spec:
  podSelector:
    matchLabels:
      run: backend 
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: frontend 
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          ns: cassandra
#      podSelector: 
 #       matchLabels: 
  #        ns: backend
