apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-pod
  name: sample-pod
spec:
  serviceAccount: default 
  containers:
  - image: ubuntu
    name: sample-pod
    command: ["sleep", "3600"]
    securityContext: 
     privileged: false
  #   runAsUser: 0
 #    capabilities: 
#      add: ["CAP_SYS_BOOT"]
#  volumes: 
  #- name: data
   # hostPath: 
    # path: /data
     ##type: Directory
