apiVersion: policy/v1beta1 
kind: PodSecurityPolicy 
metadata:
 name: example-psp 
spec : 
 privileged: false 
 seLinux: 
  rule: RunAsAny 
 supplementalGroups : 
  rule: RunAsAny 
 runAsUser: 
  rule: RunAsAny 
# requiredDropCapabilities:
 #- 'CAP_SYS_BOOT'
 defaultAddCapabilities:
 - 'CAP_SYS_TIME'
 volumes: 
 - '*'
 fsGroup: 
  rule: RunAsAny
