apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: psproleb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psprole
subjects:
- kind: ServiceAccount
  name: default
  namespace: mayank
