apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodename
  name: nodeselector
spec:
  nodeSelector: 
   app: mayank
  containers:
  - image: nginx
    name: nodename
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
