apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: noschedule
  name: noschedule
spec:
  containers:
  - image: nginx
    name: noschedule
  tolerations: 
  - key: mayank
    value: training
    operator: Equal
    effect: NoSchedule
